# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skaltraz/eclipse-workspace/ImacWars

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skaltraz/eclipse-workspace/ImacWars

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skaltraz/eclipse-workspace/ImacWars/CMakeFiles /home/skaltraz/eclipse-workspace/ImacWars/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skaltraz/eclipse-workspace/ImacWars/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imacwars

# Build rule for target.
imacwars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imacwars
.PHONY : imacwars

# fast build rule for target.
imacwars/fast:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/build
.PHONY : imacwars/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/Controller.o: src/Controller.cpp.o

.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Controller.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i

.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Controller.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s

.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Controller.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/Exceptions.o: src/Exceptions.cpp.o

.PHONY : src/Exceptions.o

# target to build an object file
src/Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Exceptions.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Exceptions.cpp.o
.PHONY : src/Exceptions.cpp.o

src/Exceptions.i: src/Exceptions.cpp.i

.PHONY : src/Exceptions.i

# target to preprocess a source file
src/Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Exceptions.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Exceptions.cpp.i
.PHONY : src/Exceptions.cpp.i

src/Exceptions.s: src/Exceptions.cpp.s

.PHONY : src/Exceptions.s

# target to generate assembly for a file
src/Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Exceptions.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Exceptions.cpp.s
.PHONY : src/Exceptions.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Model.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Model.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Model.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Player.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Player.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Player.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Tile.o: src/Tile.cpp.o

.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Tile.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i

.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Tile.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s

.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Tile.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

src/Unit.o: src/Unit.cpp.o

.PHONY : src/Unit.o

# target to build an object file
src/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Unit.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Unit.cpp.o
.PHONY : src/Unit.cpp.o

src/Unit.i: src/Unit.cpp.i

.PHONY : src/Unit.i

# target to preprocess a source file
src/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Unit.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Unit.cpp.i
.PHONY : src/Unit.cpp.i

src/Unit.s: src/Unit.cpp.s

.PHONY : src/Unit.s

# target to generate assembly for a file
src/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Unit.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Unit.cpp.s
.PHONY : src/Unit.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Util.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Util.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/Util.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/View.o: src/View.cpp.o

.PHONY : src/View.o

# target to build an object file
src/View.cpp.o:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/View.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/View.cpp.o
.PHONY : src/View.cpp.o

src/View.i: src/View.cpp.i

.PHONY : src/View.i

# target to preprocess a source file
src/View.cpp.i:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/View.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/View.cpp.i
.PHONY : src/View.cpp.i

src/View.s: src/View.cpp.s

.PHONY : src/View.s

# target to generate assembly for a file
src/View.cpp.s:
	$(MAKE) -f CMakeFiles/imacwars.dir/build.make CMakeFiles/imacwars.dir/src/View.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/View.cpp.s
.PHONY : src/View.cpp.s

test/AllTests.o: test/AllTests.cpp.o

.PHONY : test/AllTests.o

# target to build an object file
test/AllTests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/AllTests.cpp.o
.PHONY : test/AllTests.cpp.o

test/AllTests.i: test/AllTests.cpp.i

.PHONY : test/AllTests.i

# target to preprocess a source file
test/AllTests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/AllTests.cpp.i
.PHONY : test/AllTests.cpp.i

test/AllTests.s: test/AllTests.cpp.s

.PHONY : test/AllTests.s

# target to generate assembly for a file
test/AllTests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/AllTests.cpp.s
.PHONY : test/AllTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... imacwars"
	@echo "... tests"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/Exceptions.o"
	@echo "... src/Exceptions.i"
	@echo "... src/Exceptions.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
	@echo "... src/Unit.o"
	@echo "... src/Unit.i"
	@echo "... src/Unit.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/View.o"
	@echo "... src/View.i"
	@echo "... src/View.s"
	@echo "... test/AllTests.o"
	@echo "... test/AllTests.i"
	@echo "... test/AllTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

